services:
  ass:
    build:
      context: ./ass
      dockerfile: ./Dockerfile
    ports:
      - "${DIDT_APP_PORT:-8019}:8019"
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./face/dist:/dist
    depends_on:
      db:
        condition: service_healthy
    networks:
      - didt
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - didt
volumes:
  db-data:
networks:
  didt:
    driver: bridge
